AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LambdaMethodHandler::handleRequest
      Runtime: java8
      Timeout: 30
      MemorySize: 128
      CodeUri: target//HelloLambda-1.0-SNAPSHOT.jar
      Policies:
              - AWSLambdaExecute